language: php

git:
  quiet: true
  depth: 3

matrix:
  fast_finish: true
  include:
  - php: 5.6
  - php: 7.0 # PHPUnit 7 by default
    env: PHPUNIT_BIN=~/bin/phpunit-6.5.14.phar
  - php: 7.1 # PHPUnit 8 by default
    env: PHPUNIT_BIN=~/bin/phpunit-7.5.16.phar
  - php: 7.2 # PHPUnit 8 by default
    env: PHPUNIT_BIN=~/bin/phpunit-7.5.16.phar
  - php: 7.3 # PHPUnit 8 by default
    env: PHPUNIT_BIN=~/bin/phpunit-7.5.16.phar

services:
 - mysql

before_script:
 - ./tests/travis_setup_mysql.sh racktables_unittest racktables travistest
 - if [ "$PHPUNIT_BIN" != "" ]; then mkdir -p ~/bin && curl -sSfL -o "$PHPUNIT_BIN" https://phar.phpunit.de/${PHPUNIT_BIN##~/bin/} && chmod a+x "$PHPUNIT_BIN"; fi

script:
 - ./tests/express_pre.sh
 - if [ "$SKIP_PHPUNIT" = yes ]; then echo '(skipped PHPUnit tests on request)'; else ./tests/express_phpunit.sh; fi
 - ./tests/express_post.sh
 - mysql -u racktables -ptravistest racktables_unittest < scripts/init-sample-racks.sql
 - DESTDIR=/tmp make install
