language: php

git:
  quiet: true
  depth: 3

php:
 - 5.4
 - 5.5
 - 5.6
 - 7.0.15 # PHPUnit 5
 - 7.0    # PHPUnit 6
 - 7.1

matrix:
  fast_finish: true
  allow_failures:
   - php: 7.1

services:
 - mysql

before_script:
 - ./tests/travis_setup_mysql.sh racktables_unittest racktables travistest

script:
 - ./tests/express.sh
 - mysql -u racktables -ptravistest racktables_unittest < scripts/init-sample-racks.sql
 - DESTDIR=/tmp make install
